import type * as Monaco from "monaco-editor";

export interface EditorTheme {
  id: string;
  label: string;
  accent: string; // color used for the dot/swatch in the dropdown
  base: "vs-dark" | "vs" | "hc-black";
  themeData: Monaco.editor.IStandaloneThemeData;
}

// ─── Custom built-in theme ────────────────────────────────────────────────────
const devforgeDark: Monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "4a4a5e", fontStyle: "italic" },
    { token: "keyword", foreground: "fb923c" },
    { token: "string", foreground: "86efac" },
    { token: "number", foreground: "7dd3fc" },
    { token: "type", foreground: "c4b5fd" },
    { token: "function", foreground: "fde68a" },
  ],
  colors: {
    "editor.background": "#0e0e12",
    "editor.foreground": "#d4d4e8",
    "editorLineNumber.foreground": "#2e2e3e",
    "editorLineNumber.activeForeground": "#fb923c",
    "editor.lineHighlightBackground": "#141420",
    "editorCursor.foreground": "#fb923c",
    "editor.selectionBackground": "#fb923c28",
    "editorGutter.background": "#0e0e12",
    "editorWidget.background": "#16161e",
    "editorSuggestWidget.background": "#16161e",
    "editorSuggestWidget.border": "#2a2a38",
    "editorSuggestWidget.selectedBackground": "#1e1e2e",
  },
};

const nightOwl: Monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "637777", fontStyle: "italic" },
    { token: "keyword", foreground: "c792ea" },
    { token: "string", foreground: "ecc48d" },
    { token: "number", foreground: "f78c6c" },
    { token: "type", foreground: "ffcb8b" },
    { token: "function", foreground: "82aaff" },
    { token: "variable", foreground: "addb67" },
    { token: "operator", foreground: "7fdbca" },
  ],
  colors: {
    "editor.background": "#011627",
    "editor.foreground": "#d6deeb",
    "editorLineNumber.foreground": "#1d3b53",
    "editorLineNumber.activeForeground": "#c5e4fd",
    "editor.lineHighlightBackground": "#0b2942",
    "editorCursor.foreground": "#80a4c2",
    "editor.selectionBackground": "#1d3b5380",
    "editorGutter.background": "#011627",
    "editorWidget.background": "#04253a",
    "editorSuggestWidget.background": "#04253a",
    "editorSuggestWidget.border": "#1d3b53",
    "editorSuggestWidget.selectedBackground": "#0b2942",
  },
};

const roseGlass: Monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "6b4f5e", fontStyle: "italic" },
    { token: "keyword", foreground: "f4a7b9" },
    { token: "string", foreground: "f9c8d4" },
    { token: "number", foreground: "ffb7c5" },
    { token: "type", foreground: "e8a0b4" },
    { token: "function", foreground: "ffd6df" },
    { token: "variable", foreground: "f7c5d0" },
  ],
  colors: {
    "editor.background": "#180d12",
    "editor.foreground": "#f5dde5",
    "editorLineNumber.foreground": "#3a1c26",
    "editorLineNumber.activeForeground": "#f4a7b9",
    "editor.lineHighlightBackground": "#1f0e16",
    "editorCursor.foreground": "#f4a7b9",
    "editor.selectionBackground": "#f4a7b930",
    "editorGutter.background": "#180d12",
    "editorWidget.background": "#220e18",
    "editorSuggestWidget.background": "#220e18",
    "editorSuggestWidget.border": "#3a1c26",
    "editorSuggestWidget.selectedBackground": "#2c1220",
  },
};

const arcticIce: Monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "4c6680", fontStyle: "italic" },
    { token: "keyword", foreground: "88c0d0" },
    { token: "string", foreground: "a3be8c" },
    { token: "number", foreground: "b48ead" },
    { token: "type", foreground: "ebcb8b" },
    { token: "function", foreground: "81a1c1" },
    { token: "variable", foreground: "d8dee9" },
    { token: "operator", foreground: "81a1c1" },
  ],
  colors: {
    "editor.background": "#1e2128",
    "editor.foreground": "#d8dee9",
    "editorLineNumber.foreground": "#3b4252",
    "editorLineNumber.activeForeground": "#88c0d0",
    "editor.lineHighlightBackground": "#252a33",
    "editorCursor.foreground": "#88c0d0",
    "editor.selectionBackground": "#434c5e80",
    "editorGutter.background": "#1e2128",
    "editorWidget.background": "#252a33",
    "editorSuggestWidget.background": "#252a33",
    "editorSuggestWidget.border": "#3b4252",
    "editorSuggestWidget.selectedBackground": "#2e3440",
  },
};

const cyberPunk: Monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "3d3d5c", fontStyle: "italic" },
    { token: "keyword", foreground: "ff2d78" },
    { token: "string", foreground: "00ff9c" },
    { token: "number", foreground: "ffe74c" },
    { token: "type", foreground: "bf5af2" },
    { token: "function", foreground: "0af5ff" },
    { token: "variable", foreground: "e2e2e8" },
    { token: "operator", foreground: "ff2d78" },
  ],
  colors: {
    "editor.background": "#080810",
    "editor.foreground": "#e2e2f0",
    "editorLineNumber.foreground": "#1e1e3a",
    "editorLineNumber.activeForeground": "#ff2d78",
    "editor.lineHighlightBackground": "#0d0d1e",
    "editorCursor.foreground": "#ff2d78",
    "editor.selectionBackground": "#ff2d7830",
    "editorGutter.background": "#080810",
    "editorWidget.background": "#0d0d1e",
    "editorSuggestWidget.background": "#0d0d1e",
    "editorSuggestWidget.border": "#1e1e3a",
    "editorSuggestWidget.selectedBackground": "#14142a",
  },
};

const forestDark: Monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "4a6741", fontStyle: "italic" },
    { token: "keyword", foreground: "98c379" },
    { token: "string", foreground: "d19a66" },
    { token: "number", foreground: "61afef" },
    { token: "type", foreground: "e5c07b" },
    { token: "function", foreground: "56b6c2" },
    { token: "variable", foreground: "abb2bf" },
    { token: "operator", foreground: "c678dd" },
  ],
  colors: {
    "editor.background": "#0d1a0d",
    "editor.foreground": "#abb2bf",
    "editorLineNumber.foreground": "#1e3a1e",
    "editorLineNumber.activeForeground": "#98c379",
    "editor.lineHighlightBackground": "#111f11",
    "editorCursor.foreground": "#98c379",
    "editor.selectionBackground": "#98c37930",
    "editorGutter.background": "#0d1a0d",
    "editorWidget.background": "#111f11",
    "editorSuggestWidget.background": "#111f11",
    "editorSuggestWidget.border": "#1e3a1e",
    "editorSuggestWidget.selectedBackground": "#162616",
  },
};

const sandstorm: Monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "5c4f3a", fontStyle: "italic" },
    { token: "keyword", foreground: "e5a550" },
    { token: "string", foreground: "c5a882" },
    { token: "number", foreground: "d4915a" },
    { token: "type", foreground: "e8c87a" },
    { token: "function", foreground: "f0d080" },
    { token: "variable", foreground: "d4c4a8" },
  ],
  colors: {
    "editor.background": "#1a1208",
    "editor.foreground": "#d4c4a8",
    "editorLineNumber.foreground": "#3a2e1c",
    "editorLineNumber.activeForeground": "#e5a550",
    "editor.lineHighlightBackground": "#1f1610",
    "editorCursor.foreground": "#e5a550",
    "editor.selectionBackground": "#e5a55030",
    "editorGutter.background": "#1a1208",
    "editorWidget.background": "#1f1610",
    "editorSuggestWidget.background": "#1f1610",
    "editorSuggestWidget.border": "#3a2e1c",
    "editorSuggestWidget.selectedBackground": "#2a1e0e",
  },
};

const dracula: Monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "6272a4", fontStyle: "italic" },
    { token: "keyword", foreground: "ff79c6" },
    { token: "storage", foreground: "ff79c6" },
    { token: "string", foreground: "f1fa8c" },
    { token: "number", foreground: "bd93f9" },
    { token: "constant", foreground: "bd93f9" },
    { token: "type", foreground: "8be9fd", fontStyle: "italic" },
    { token: "function", foreground: "50fa7b" },
    { token: "variable", foreground: "ffb86c" },
    { token: "variable.parameter", foreground: "ffb86c", fontStyle: "italic" },
    { token: "entity.name.tag", foreground: "ff79c6" },
    { token: "entity.name.class", foreground: "50fa7b" },
    { token: "support.function", foreground: "8be9fd" },
    { token: "operator", foreground: "ff79c6" },
  ],
  colors: {
    "editor.background": "#282a36",
    "editor.foreground": "#f8f8f2",
    "editorLineNumber.foreground": "#44475a",
    "editorLineNumber.activeForeground": "#bd93f9",
    "editor.lineHighlightBackground": "#44475a",
    "editorCursor.foreground": "#f8f8f0",
    "editor.selectionBackground": "#44475a",
    "editorGutter.background": "#282a36",
    "editorWidget.background": "#21222c",
    "editorSuggestWidget.background": "#21222c",
    "editorSuggestWidget.border": "#44475a",
    "editorSuggestWidget.selectedBackground": "#44475a",
  },
};

// ─── MEDIUM-LIGHT THEMES (darker & more comfortable) ─────────────────────────

const breeze: Monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "comment", foreground: "6b7a8f", fontStyle: "italic" },
    { token: "keyword", foreground: "0ea5e9" },
    { token: "string", foreground: "4ade80" },
    { token: "number", foreground: "fb923c" },
    { token: "type", foreground: "8b5cf6" },
    { token: "function", foreground: "ec489a" },
    { token: "variable", foreground: "1e293b" },
    { token: "operator", foreground: "0ea5e9" },
  ],
  colors: {
    "editor.background": "#e0e7f0",
    "editor.foreground": "#1e293b",
    "editorLineNumber.foreground": "#94a3b8",
    "editorLineNumber.activeForeground": "#0ea5e9",
    "editor.lineHighlightBackground": "#d1dbe9",
    "editorCursor.foreground": "#0ea5e9",
    "editor.selectionBackground": "#0ea5e930",
    "editorGutter.background": "#e0e7f0",
    "editorWidget.background": "#f0f4fa",
    "editorSuggestWidget.background": "#f8fafd",
    "editorSuggestWidget.border": "#cbd5e1",
    "editorSuggestWidget.selectedBackground": "#e2e8f0",
  },
};

const mist: Monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "comment", foreground: "6f7f5f", fontStyle: "italic" },
    { token: "keyword", foreground: "4ade80" },
    { token: "string", foreground: "fb923c" },
    { token: "number", foreground: "facc15" },
    { token: "type", foreground: "3b82f6" },
    { token: "function", foreground: "a855f7" },
    { token: "variable", foreground: "1f2a1f" },
    { token: "operator", foreground: "4ade80" },
  ],
  colors: {
    "editor.background": "#e4e9df",
    "editor.foreground": "#1f2a1f",
    "editorLineNumber.foreground": "#9bad8a",
    "editorLineNumber.activeForeground": "#4ade80",
    "editor.lineHighlightBackground": "#d8e0d2",
    "editorCursor.foreground": "#4ade80",
    "editor.selectionBackground": "#4ade8030",
    "editorGutter.background": "#e4e9df",
    "editorWidget.background": "#eef2e9",
    "editorSuggestWidget.background": "#f6f9f2",
    "editorSuggestWidget.border": "#c8d4b9",
    "editorSuggestWidget.selectedBackground": "#dbe3d3",
  },
};

const rose: Monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "comment", foreground: "9c7a7a", fontStyle: "italic" },
    { token: "keyword", foreground: "f43f5e" },
    { token: "string", foreground: "fb923c" },
    { token: "number", foreground: "f97316" },
    { token: "type", foreground: "a855f7" },
    { token: "function", foreground: "ec489a" },
    { token: "variable", foreground: "2d1f1f" },
    { token: "operator", foreground: "f43f5e" },
  ],
  colors: {
    "editor.background": "#f2e4e4",
    "editor.foreground": "#2d1f1f",
    "editorLineNumber.foreground": "#d4b8b8",
    "editorLineNumber.activeForeground": "#f43f5e",
    "editor.lineHighlightBackground": "#e8d6d6",
    "editorCursor.foreground": "#f43f5e",
    "editor.selectionBackground": "#f43f5e30",
    "editorGutter.background": "#f2e4e4",
    "editorWidget.background": "#f8ecec",
    "editorSuggestWidget.background": "#fdf4f4",
    "editorSuggestWidget.border": "#e0c6c6",
    "editorSuggestWidget.selectedBackground": "#f0dcdc",
  },
};

const lavender: Monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "comment", foreground: "8a7eb0", fontStyle: "italic" },
    { token: "keyword", foreground: "a78bfa" },
    { token: "string", foreground: "14b8a5" },
    { token: "number", foreground: "f97316" },
    { token: "type", foreground: "8b5cf6" },
    { token: "function", foreground: "ec489a" },
    { token: "variable", foreground: "26223a" },
    { token: "operator", foreground: "a78bfa" },
  ],
  colors: {
    "editor.background": "#e8e4f5",
    "editor.foreground": "#26223a",
    "editorLineNumber.foreground": "#c4b8e0",
    "editorLineNumber.activeForeground": "#a78bfa",
    "editor.lineHighlightBackground": "#dcd6f0",
    "editorCursor.foreground": "#a78bfa",
    "editor.selectionBackground": "#a78bfa30",
    "editorGutter.background": "#e8e4f5",
    "editorWidget.background": "#f0ebf9",
    "editorSuggestWidget.background": "#f8f5fe",
    "editorSuggestWidget.border": "#d1c6e8",
    "editorSuggestWidget.selectedBackground": "#e4def5",
  },
};

const cotton: Monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "comment", foreground: "7f7f9e", fontStyle: "italic" },
    { token: "keyword", foreground: "4f46e5" },
    { token: "string", foreground: "ec489a" },
    { token: "number", foreground: "f97316" },
    { token: "type", foreground: "06b6d4" },
    { token: "function", foreground: "8b5cf6" },
    { token: "variable", foreground: "252537" },
    { token: "operator", foreground: "4f46e5" },
  ],
  colors: {
    "editor.background": "#e6e6f0",
    "editor.foreground": "#252537",
    "editorLineNumber.foreground": "#b8b8d0",
    "editorLineNumber.activeForeground": "#4f46e5",
    "editor.lineHighlightBackground": "#d8d8e6",
    "editorCursor.foreground": "#4f46e5",
    "editor.selectionBackground": "#4f46e530",
    "editorGutter.background": "#e6e6f0",
    "editorWidget.background": "#f0f0f8",
    "editorSuggestWidget.background": "#f8f8fe",
    "editorSuggestWidget.border": "#c8c8e0",
    "editorSuggestWidget.selectedBackground": "#e0e0ec",
  },
};

const honey: Monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "comment", foreground: "a07f5f", fontStyle: "italic" },
    { token: "keyword", foreground: "eab308" },
    { token: "string", foreground: "fb923c" },
    { token: "number", foreground: "f59e0b" },
    { token: "type", foreground: "84cc16" },
    { token: "function", foreground: "f59e0b" },
    { token: "variable", foreground: "3a2a18" },
    { token: "operator", foreground: "eab308" },
  ],
  colors: {
    "editor.background": "#f0e6d4",
    "editor.foreground": "#3a2a18",
    "editorLineNumber.foreground": "#d4c4a0",
    "editorLineNumber.activeForeground": "#eab308",
    "editor.lineHighlightBackground": "#e6d9c2",
    "editorCursor.foreground": "#eab308",
    "editor.selectionBackground": "#eab30830",
    "editorGutter.background": "#f0e6d4",
    "editorWidget.background": "#f8f0e0",
    "editorSuggestWidget.background": "#fdf8ec",
    "editorSuggestWidget.border": "#e0d0b0",
    "editorSuggestWidget.selectedBackground": "#f0e0c8",
  },
};

const mint: Monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "comment", foreground: "7eb8a8", fontStyle: "italic" },
    { token: "keyword", foreground: "14b8a6" },
    { token: "string", foreground: "4ade80" },
    { token: "number", foreground: "fb923c" },
    { token: "type", foreground: "8b5cf6" },
    { token: "function", foreground: "06b6d4" },
    { token: "variable", foreground: "1e4642" },
    { token: "operator", foreground: "14b8a6" },
  ],
  colors: {
    "editor.background": "#e0f0eb",
    "editor.foreground": "#1e4642",
    "editorLineNumber.foreground": "#a8d4c8",
    "editorLineNumber.activeForeground": "#14b8a6",
    "editor.lineHighlightBackground": "#d0e8e2",
    "editorCursor.foreground": "#14b8a6",
    "editor.selectionBackground": "#14b8a630",
    "editorGutter.background": "#e0f0eb",
    "editorWidget.background": "#e8f5f1",
    "editorSuggestWidget.background": "#f0faf6",
    "editorSuggestWidget.border": "#b8e0d4",
    "editorSuggestWidget.selectedBackground": "#d8ece6",
  },
};

const peach: Monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "comment", foreground: "b38a6f", fontStyle: "italic" },
    { token: "keyword", foreground: "f97316" },
    { token: "string", foreground: "4ade80" },
    { token: "number", foreground: "eab308" },
    { token: "type", foreground: "06b6d4" },
    { token: "function", foreground: "a855f7" },
    { token: "variable", foreground: "3b2a1f" },
    { token: "operator", foreground: "f97316" },
  ],
  colors: {
    "editor.background": "#f0e4d8",
    "editor.foreground": "#3b2a1f",
    "editorLineNumber.foreground": "#d8c8b0",
    "editorLineNumber.activeForeground": "#f97316",
    "editor.lineHighlightBackground": "#e6d4c2",
    "editorCursor.foreground": "#f97316",
    "editor.selectionBackground": "#f9731630",
    "editorGutter.background": "#f0e4d8",
    "editorWidget.background": "#f8ede0",
    "editorSuggestWidget.background": "#fdf6ec",
    "editorSuggestWidget.border": "#e0c8a8",
    "editorSuggestWidget.selectedBackground": "#f0dcc8",
  },
};

const frost: Monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "comment", foreground: "7e9ab8", fontStyle: "italic" },
    { token: "keyword", foreground: "06b6d4" },
    { token: "string", foreground: "4ade80" },
    { token: "number", foreground: "fb923c" },
    { token: "type", foreground: "a855f7" },
    { token: "function", foreground: "8b5cf6" },
    { token: "variable", foreground: "1e2e3e" },
    { token: "operator", foreground: "06b6d4" },
  ],
  colors: {
    "editor.background": "#e4ecf7",
    "editor.foreground": "#1e2e3e",
    "editorLineNumber.foreground": "#b8cce4",
    "editorLineNumber.activeForeground": "#06b6d4",
    "editor.lineHighlightBackground": "#d6e2f0",
    "editorCursor.foreground": "#06b6d4",
    "editor.selectionBackground": "#06b6d430",
    "editorGutter.background": "#e4ecf7",
    "editorWidget.background": "#ecf2f9",
    "editorSuggestWidget.background": "#f4f9fe",
    "editorSuggestWidget.border": "#c8d8ec",
    "editorSuggestWidget.selectedBackground": "#dce6f2",
  },
};

const stone: Monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "comment", foreground: "#9c8f7f", fontStyle: "italic" },
    { token: "keyword", foreground: "#78716c" },
    { token: "string", foreground: "#d97706" },
    { token: "number", foreground: "#f97316" },
    { token: "type", foreground: "#8b5cf6" },
    { token: "function", foreground: "#a855f7" },
    { token: "variable", foreground: "#2b2520" },
    { token: "operator", foreground: "#78716c" },
  ],
  colors: {
    "editor.background": "#ebe6e0",
    "editor.foreground": "#2b2520",
    "editorLineNumber.foreground": "#d1c6b8",
    "editorLineNumber.activeForeground": "#78716c",
    "editor.lineHighlightBackground": "#e2dad2",
    "editorCursor.foreground": "#78716c",
    "editor.selectionBackground": "#78716c30",
    "editorGutter.background": "#ebe6e0",
    "editorWidget.background": "#f2ede6",
    "editorSuggestWidget.background": "#f8f5f0",
    "editorSuggestWidget.border": "#d9d0c4",
    "editorSuggestWidget.selectedBackground": "#e6e0d6",
  },
};

const oceanBreeze: Monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "comment", foreground: "#7e96b8", fontStyle: "italic" },
    { token: "keyword", foreground: "#3b82f6" },
    { token: "string", foreground: "#4ade80" },
    { token: "number", foreground: "#fb923c" },
    { token: "type", foreground: "#8b5cf6" },
    { token: "function", foreground: "#ec489a" },
    { token: "variable", foreground: "#1e2a3a" },
    { token: "operator", foreground: "#3b82f6" },
  ],
  colors: {
    "editor.background": "#e4ebf8",
    "editor.foreground": "#1e2a3a",
    "editorLineNumber.foreground": "#b8cce8",
    "editorLineNumber.activeForeground": "#3b82f6",
    "editor.lineHighlightBackground": "#d6e2f2",
    "editorCursor.foreground": "#3b82f6",
    "editor.selectionBackground": "#3b82f630",
    "editorGutter.background": "#e4ebf8",
    "editorWidget.background": "#ecf2fb",
    "editorSuggestWidget.background": "#f4f9fe",
    "editorSuggestWidget.border": "#c8d8f0",
    "editorSuggestWidget.selectedBackground": "#dce6f4",
  },
};

// ─── Theme Registry ───────────────────────────────────────────────────────────
export const EDITOR_THEMES: EditorTheme[] = [
  // Dark themes
  {
    id: "devforge-dark",
    label: "DevForge",
    accent: "#fb923c",
    base: "vs-dark",
    themeData: devforgeDark,
  },
  {
    id: "night-owl",
    label: "Night Owl",
    accent: "#82aaff",
    base: "vs-dark",
    themeData: nightOwl,
  },
  {
    id: "arctic-ice",
    label: "Arctic Ice",
    accent: "#88c0d0",
    base: "vs-dark",
    themeData: arcticIce,
  },
  {
    id: "forest-dark",
    label: "Forest",
    accent: "#98c379",
    base: "vs-dark",
    themeData: forestDark,
  },
  {
    id: "cyberpunk",
    label: "Cyberpunk",
    accent: "#ff2d78",
    base: "vs-dark",
    themeData: cyberPunk,
  },
  {
    id: "rose-glass",
    label: "Rose Glass",
    accent: "#f4a7b9",
    base: "vs-dark",
    themeData: roseGlass,
  },
  {
    id: "sandstorm",
    label: "Sandstorm",
    accent: "#e5a550",
    base: "vs-dark",
    themeData: sandstorm,
  },
  {
    id: "dracula",
    label: "Dracula",
    accent: "#bd93f9",
    base: "vs-dark",
    themeData: dracula,
  },
  // Medium-light themes (now darker)
  {
    id: "breeze",
    label: "Breeze",
    accent: "#0ea5e9",
    base: "vs",
    themeData: breeze,
  },
  {
    id: "mist",
    label: "Mist",
    accent: "#84cc16",
    base: "vs",
    themeData: mist,
  },
  {
    id: "rose",
    label: "Rose",
    accent: "#f43f5e",
    base: "vs",
    themeData: rose,
  },
  {
    id: "lavender",
    label: "Lavender",
    accent: "#a78bfa",
    base: "vs",
    themeData: lavender,
  },
  {
    id: "cotton",
    label: "Cotton",
    accent: "#4f46e5",
    base: "vs",
    themeData: cotton,
  },
  {
    id: "honey",
    label: "Honey",
    accent: "#eab308",
    base: "vs",
    themeData: honey,
  },
  {
    id: "mint",
    label: "Mint",
    accent: "#14b8a6",
    base: "vs",
    themeData: mint,
  },
  {
    id: "peach",
    label: "Peach",
    accent: "#f97316",
    base: "vs",
    themeData: peach,
  },
  {
    id: "frost",
    label: "Frost",
    accent: "#06b6d4",
    base: "vs",
    themeData: frost,
  },
  {
    id: "stone",
    label: "Stone",
    accent: "#78716c",
    base: "vs",
    themeData: stone,
  },
  {
    id: "ocean-breeze",
    label: "Ocean Breeze",
    accent: "#3b82f6",
    base: "vs",
    themeData: oceanBreeze,
  },
];

export const DEFAULT_THEME_ID = "devforge-dark";

export function registerAllThemes(monaco: typeof import("monaco-editor")) {
  for (const theme of EDITOR_THEMES) {
    monaco.editor.defineTheme(theme.id, theme.themeData);
  }
}
